create table users (
    user_id uuid primary key not null references auth.users on delete cascade,
    username text unique
);

create table private_projects (
    project_id bigint generated by default as identity primary key,
    project_name text,
    project_owner uuid not null references users,
    project_bot uuid references auth.users on delete cascade,
    project_data jsonb
);

create table private_members (
    relation_id bigint generated by default as identity primary key,
    project_id bigint not null references private_projects,
    member_id uuid not null references users
);

create table public_projects (
    project_id bigint generated by default as identity primary key,
    project_name text,
    project_owner uuid not null references users,
    project_bot uuid references auth.users on delete cascade,
    project_data jsonb
);

alter table users enable row level security;
alter table private_projects enable row level security;
alter table private_members enable row level security;
alter table public_projects enable row level security;
